### PR TITLE
A new search algorithm, and some cleanups

### PR DESCRIPTION
**Pull request by mjtorn**
Hi!

Cool stuff you have going here, but I have trouble finding my keys with it. I have nearly 100 passwords stored, so I figured I could replace the `find` magic with a simple algorithm.

Works miracles for me, wanna give it a shot and maybe release it if it's ok?

Thanks!

### CODE REVIEW

**Comment by yeoldegrove** [comment]
@mjtorn Thank you for this PR. Will check it out.

**Comment by mjtorn** [comment]
Cheers! I'm happy to answer questions if you have any, and whatever it takes to get this in. I'm already using this so I hope I don't have to have a fork for this ;)

**Comment by mjtorn** [comment]
I fixed a bug in it. Hope you don't hate it, as I believe the code is significantly better now.

**Comment by mjtorn** [comment]
Now I force-pushed an optimization; there was a variable `found_count` which was compared to `need` to see if we found all we need. This could be eliminated and change the `need` semantics to mean "how many do we still need".

I really hope I don't have to obsess over this any more and you can review it in peace :) Sorry about the fuss!

**Comment by mjtorn** [comment]
But I couldn't help myself and eliminated `need` altogether...

**Comment by yeoldegrove** [comment]
Thank you very much for your contribution.
Also fixed some tiny bits and will make a new release soon.

**Comment by mjtorn** [comment]
Thank you for merging and looking forward to the next release!

**Pull request merged**
